name: Build 🔨
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout repo

      - name: Set up JDK 17 (LTS)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn package --batch-mode

      - uses: actions/upload-artifact@v2
        name: Upload Artifact
        with:
          name: CrazyAuctionsPlus.jar
          path: target/CrazyAuctionsPlus-*.jar
